name: Reward
version: 0.1
author: creekorful
description: basic minecraft plugin that add reward in game
main: fr.creekorful.reward.Reward

commands:
   reward:
      description: reward command

   reward add:
      description: Add player to reward list
      usage: /reward <add> [playerName] [severity] [bounty]

   reward remove:
      description: Remove player from reward list
      usage: /reward remove <playerName>

   reward list:
      description: list all rewarded players
      usage: /reward list

   reward save:
      description: save all players to dao unit
      usage: /reward save

   reward reload:
      description: load all players from dao unit
      usage: /reward reload